version: "3"
services: 
    ros-core:
        image: ros:melodic-ros-core-stretch
        command: roscore
        network_mode: "host"
    ros-moveit-desktop:
        build: .
        image: taityo/ros-moveit-desktop
        volumes: 
            - $HOME/.Xauthority:/home/taicho/.Xauthority:rw
        user: 1000:1000 # uid:gid
        environment: 
            - ROS_MASTER_URI=http://localhost:11311
            - ROS_IP=192.168.189.76
            - DISPLAY=$DISPLAY
            - USER=taicho
            - PASSWORD=Mikocchan1
#            - WORKDIR=/home/ws_moveit
#        working_dir: /home/ws_moveit
        network_mode: "host"
        tty: true