version: "3"
services: 
    ros-core:
        image: ros:melodic-ros-core-stretch
        command: roscore
        network_mode: "host"
    ros-moveit:
        build: .
        image: taityo/ros-moveit
        volumes:
            - $HOME/.Xauthority:/root/.Xauthority:rw
        environment: 
            - ROS_MASTER_URI=http://localhost:11311
            - ROS_IP=192.168.189.76
            - DISPLAY=$DISPLAY
#            - WORKDIR=/home/ws_moveit
#        working_dir: /home/ws_moveit
        network_mode: "host"
        tty: true
