version: "3"
services: 
    ros2:
        build: .
#        image: taityo/ros2-desktop
        image: osrf/ros2:devel
        environment: 
            - ROS_DOMAIN_ID=1
            - DISPLAY=novnc:0.0
#        network_mode: "host"
#        volumes: 
#            - .:/opt/ros2_ws/src/ros2
        depends_on:
            - novnc
        tty: true
    novnc:
        image: gramaziokohler/novnc
#        image: ct2034/vnc-ros-kinetic-full
        ports: 
#            - 6080:80
            - 6080:8080