version: "3"
services: 
    ros-core:
        image: ros:melodic-ros-core-stretch
        command: roscore
        network_mode: "host"
    ros-desktop-full:
        build: .
        image: taityo/ros-desktop-full
        volumes: 
            - $HOME/.Xauthority:/root/.Xauthority:rw
        environment: 
            - ROS_MASTER_URI=http://localhost:11311
            - ROS_IP=192.168.189.76
            - DISPLAY=$DISPLAY
        network_mode: "host"
        tty: true

